spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/product
#    url: jdbc:mysql://localhost:3307/product
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata

server:
  port: 8081